SELECT TOP (1000) [Restaurant_Name]
      ,[Inspection_Type]
      ,[Inspection_Date]
      ,[Inspection_Date_new]
      ,[Inspection_Score]
      ,[Street_Number]
      ,[Street_Name]
      ,[Street_Direction]
      ,[Street_Type]
      ,[Street_Unit]
      ,[Street_Address]
      ,[Zip_Code]
      ,[Violation_Description___1]
      ,[Violation_Points___1]
      ,[Violation_Detail___1]
      ,[Violation_Memo___1]
      ,[Violation_Description___2]
      ,[Violation_Points___2]
      ,[Violation_Detail___2]
      ,[Violation_Memo___2]
      ,[Violation_Description___3]
      ,[Violation_Points___3]
      ,[Violation_Detail___3]
      ,[Violation_Memo___3]
      ,[Violation_Description___4]
      ,[Violation_Points___4]
      ,[Violation_Detail___4]
      ,[Violation_Memo___4]
      ,[Violation_Description___5]
      ,[Violation_Points___5]
      ,[Violation_Detail___5]
      ,[Violation_Memo___5]
      ,[Violation_Description___6]
      ,[Violation_Points___6]
      ,[Violation_Detail___6]
      ,[Violation_Memo___6]
      ,[Violation_Description___7]
      ,[Violation_Points___7]
      ,[Violation_Detail___7]
      ,[Violation_Memo___7]
      ,[Violation_Description___8]
      ,[Violation_Points___8]
      ,[Violation_Detail___8]
      ,[Violation_Memo___8]
      ,[Violation_Description___9]
      ,[Violation_Points___9]
      ,[Violation_Detail___9]
      ,[Violation_Memo___9]
      ,[Violation_Description___10]
      ,[Violation_Points___10]
      ,[Violation_Detail___10]
      ,[Violation_Memo___10]
      ,[Violation_Description___11]
      ,[Violation_Points___11]
      ,[Violation_Detail___11]
      ,[Violation_Memo___11]
      ,[Violation_Description___12]
      ,[Violation_Points___12]
      ,[Violation_Detail___12]
      ,[Violation_Memo___12]
      ,[Violation_Description___13]
      ,[Violation_Points___13]
      ,[Violation_Detail___13]
      ,[Violation_Memo___13]
      ,[Violation_Description___14]
      ,[Violation_Points___14]
      ,[Violation_Detail___14]
      ,[Violation_Memo___14]
      ,[Violation_Description___15]
      ,[Violation_Points___15]
      ,[Violation_Detail___15]
      ,[Violation_Memo___15]
      ,[Violation_Description___16]
      ,[Violation_Points___16]
      ,[Violation_Detail___16]
      ,[Violation_Memo___16]
      ,[Violation_Description___17]
      ,[Violation_Points___17]
      ,[Violation_Detail___17]
      ,[Violation_Memo___17]
      ,[Violation_Description___18]
      ,[Violation_Points___18]
      ,[Violation_Detail___18]
      ,[Violation_Memo___18]
      ,[Violation_Description___19]
      ,[Violation_Points___19]
      ,[Violation_Detail___19]
      ,[Violation_Memo___19]
      ,[Violation_Description___20]
      ,[Violation_Points___20]
      ,[Violation_Detail___20]
      ,[Violation__Memo___20]
      ,[Violation_Description___21]
      ,[Violation_Points___21]
      ,[Violation_Detail___21]
      ,[Violation_Memo___21]
      ,[Violation_Description___22]
      ,[Violation_Points___22]
      ,[Violation_Detail___22]
      ,[Violation_Memo___22]
      ,[Violation_Description___23]
      ,[Violation_Points___23]
      ,[Violation_Detail___23]
      ,[Violation_Memo___23]
      ,[Violation_Description___24]
      ,[Violation_Points___24]
      ,[Violation_Detail___24]
      ,[Violation_Memo___24]
      ,[Violation_Description___25]
      ,[Violation_Points___25]
      ,[Violation_Detail___25]
      ,[Violation_Memo___25]
      ,[Inspection_Month]
      ,[Inspection_Year]
      ,[Lat_Long_Location]
      ,[DI_CreateDate]
      ,[DI_WorkflowName]
  FROM [Food_Inspection].[dbo].[stg_Dallas_Inspection]

          SELECT 
    t.name AS TableName, 
    c.name AS ColumnName, 
    ty.name AS DataType,
    c.max_length AS Size,
    c.precision AS Precision,
    c.scale AS Scale,
    c.is_nullable AS IsNullable,
    c.is_identity AS IsIdentity
FROM 
    sys.tables t
INNER JOIN 
    sys.columns c ON t.object_id = c.object_id
INNER JOIN 
    sys.types ty ON c.user_type_id = ty.user_type_id
WHERE 
    t.name = 'stg_Dallas_Inspection'
ORDER BY 
    t.name, c.column_id;


select SCHEMA_NAME() as SchemaName;